### PR TITLE
adding RAW support to support VIS statis

### PR DESCRIPTION
**Pull request by Eisbaeeer**
The objects give feedback from eiscp in raw.

### CODE REVIEW

**Comment by instalator** [comment]
По моему это лишний и неудачный код. Драйвер сам получает все поддерживаемые ресивером команды и автоматом создает объекты для всех зон.

**Comment by instalator** [comment]
Eisbaeeer  для чего тебе нужны твои изменения?

**Comment by Eisbaeeer** [comment]
@Instalator: I wrote you more than one time, that I don´t understand russia.  Conversation in russia don´t make sense!
I asked you more than one time, how do you use this adapter with iobroker without ability to control the onkyo through VIS without the correct states?
It makes no sense to use states like "standby" and "off" in VIS!?
Please correct me, if I tell nonsens. But only states "true"|"false"|"1"|"0" are valid.
Otherwise the buttons don´t reports the correct feedback.
In first time I think, no, don´t create a new adapter, because the other developer has spend much time in it. At the moment I think about an own onkyo adapter, because this has too much overhead to do the job and I don´t see the use-case of the overhead. But that´s only my opinion.
@GermanBluefox 
You can revert the pull. I have no problems with that.

**Comment by instalator** [comment]
@Eisbaeeer 
I wrote on the forum in any condition to make vis. Write in the forum state what you want to receive in addition to power, I will help you.

**Pull request merged**
